sonar.projectKey=ai-resume-analyzer
sonar.projectName=AI Resume Analyzer
sonar.projectVersion=1.0.0
sonar.sources=app,constants
sonar.sourceEncoding=UTF-8
sonar.exclusions=build/**,node_modules/**,public/**,.react-router/**
